# Generated by Django 5.2.5 on 2025-09-04 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0006_orderitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product_name",
        ),
    ]
