# Generated by Django 5.2.5 on 2025-09-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0007_remove_orderitem_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products"),
        ),
    ]
