# Generated by Django 5.2.5 on 2025-09-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0008_alter_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(default=1, upload_to="static/images"),
            preserve_default=False,
        ),
    ]
